blueprint:
  name: "Zooz ZEN77 S2 Dimmer"
  author: jhenkens
  homeassistant: { min_version: 2023.3.1 }
  domain: automation
  description: >
    Setup actions for all the different key press combinations on the Zooz ZEN77 S2 700-series dimmer.


    Other features:

    * Local physical control can be enable/disabled

    * Configures important device settings:

      * Enables scene control (parameter 13)

      * Disables paddle programming mode (parameter 17, only on firmware 10.0+).

  input:
    device_id:
      name: Source
      description: |
        The device to add automation triggers to. 
        Note that the "Scene Control" parameter will be enabled on this device (triggered by it coming online).
      selector:
        device:
          filter: 
            - integration: zwave_js
              manufacturer: Zooz
              model: ZEN77
            - integration: zwave_js
              manufacturer: Zooz
              model: ZEN72
          multiple: false

    automation_mode:
      name: "Automation Mode"
      description: |
        Selector for Running the Automation in Single/Restart/Queued/Parallel Mode.
        Generally, Single is best for discrete button press actions, and Restart for when using hold to dim with looping.
      default: single
      selector:
        select:
          options:
            - single
            - restart
            - queued
            - parallel
          custom_value: false
          sort: false
          multiple: false

    enable_auto_configuration:
      name: "Enable automatic device configuration"
      description: Automatically configure device parameters when automation is reloaded (scene control, local programming, local control).
      default: true
      selector:
        boolean:

    local_control:
      name: "Configuration: Local phyiscal control"
      description: Enable or disable physical paddle on/off control (also known as "Smart Bulb Mode").
      default: 'undefined'
      selector:
        select:
          mode: dropdown
          options:
            - label: Do not modify configuration
              value: 'undefined'
            - label: Physical paddle control enabled (device default)
              value: '1'
            - label: Physical paddle control disabled (control via Z-Wave only)
              value: '0'

    button_1_1x:      { name: "Paddle Up press 1x",   default: [], selector: { action: {} }, description: "Action to run when the button is pressed one time. Default: Turn on load." }
    button_1_2x:      { name: "Paddle Up press 2x",   default: [], selector: { action: {} }, description: "Action to run when the button is pressed two times." }
    button_1_3x:      { name: "Paddle Up press 3x",   default: [], selector: { action: {} }, description: "Action to run when the button is pressed three times. Note: Requires firmware 10.0+." }
    button_1_4x:      { name: "Paddle Up press 4x",   default: [], selector: { action: {} }, description: "Action to run when the button is pressed four times." }
    button_1_5x:      { name: "Paddle Up press 5x",   default: [], selector: { action: {} }, description: "Action to run when the button is pressed five times." }
    button_1_hold:    { name: "Paddle Up hold",       default: [], selector: { action: {} }, description: "Action to run when the button is held. Default: Increase dimmer brightness level." }
    loop_button_1_hold:
      name: "Loop Paddle Up Hold Action?"
      description: "Asserts whether paddle up hold action should loop until button is released"
      default: false
      selector:
        boolean: {}
    button_1_loop_hold_delay:
      name: "Paddle Up Hold Loop Delay"
      description: "Delay between successive service calls while paddle up is held"
      default: 100
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: milliseconds
          mode: box
    button_1_release: { name: "Paddle Up release",    default: [], selector: { action: {} }, description: "Action to run when the button is released." }
    
    button_2_1x:      { name: "Paddle Down press 1x", default: [], selector: { action: {} }, description: "Action to run when the button is pressed one time. Default: Turn off load." }
    button_2_2x:      { name: "Paddle Down press 2x", default: [], selector: { action: {} }, description: "Action to run when the button is pressed two times." }
    button_2_3x:      { name: "Paddle Down press 3x", default: [], selector: { action: {} }, description: "Action to run when the button is pressed three times. Note: Requires firmware 10.0+." }
    button_2_4x:      { name: "Paddle Down press 4x", default: [], selector: { action: {} }, description: "Action to run when the button is pressed four times." }
    button_2_5x:      { name: "Paddle Down press 5x", default: [], selector: { action: {} }, description: "Action to run when the button is pressed five times." }
    button_2_hold:    { name: "Paddle Down hold",     default: [], selector: { action: {} }, description: "Action to run when the button is held. Default: Decrease dimmer brightness level." }
    loop_button_2_hold:
      name: "Loop Paddle Down Hold Action?"
      description: "Asserts whether paddle down hold action should loop until button is released"
      default: false
      selector:
        boolean: {}
    button_2_loop_hold_delay:
      name: "Paddle Down Hold Loop Delay"
      description: "Delay between successive service calls while paddle down is held"
      default: 100
      selector:
        number:
          min: 0
          max: 1000
          unit_of_measurement: milliseconds
          mode: box
    button_2_release: { name: "Paddle Down release",  default: [], selector: { action: {} }, description: "Action to run when the button is released." }

mode: !input automation_mode
max_exceeded: silent

variables:
  # docs: https://www.support.getzooz.com/kb/article/549-zen76-s2-on-off-switch-700-advanced-settings/
  device_id: !input device_id
  enable_auto_configuration: !input enable_auto_configuration
  local_control: !input local_control
  const_scene_control_param: 13
  const_scene_control_enable: 1
  const_local_control_param: 15
  const_local_programming_param: 26
  const_local_programming_disable: 1

trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      command_class_name: Central Scene
      device_id: !input device_id

  # used for initialization
  - platform: event
    event_type: automation_reloaded

action:
  - variables:
      #button_id: '{{ trigger.event.data.property_key_name }}'
      scene_id: "{{ trigger.event.data.label if ('event' in trigger) }}"
      event_action: "{{ trigger.event.data.value if ('event' in trigger) }}"
      is_loop_button_1_hold: !input loop_button_1_hold
      is_loop_button_2_hold: !input loop_button_2_hold
      button_1_hold: !input button_1_hold
      button_2_hold: !input button_2_hold
  - choose:
      # initialize
      - conditions: "{{ enable_auto_configuration and ('event' in trigger) and trigger.event.event_type == 'automation_reloaded' }}"
        sequence:
        
          # enable scene control
          - alias: "zwavejs: Enable scene control"
            service: zwave_js.set_config_parameter
            target: { device_id: "{{ device_id }}" }
            data: { parameter: "{{ const_scene_control_param }}", value: "{{ const_scene_control_enable }}" }

          - alias: "zwavejs: Disable local programming to allow 3-press actions. Requires Firmware 10.0+"
            service: zwave_js.set_config_parameter
            continue_on_error: true # avoid failure for older firmware
            target: { device_id: "{{ device_id }}" } 
            data: { parameter: "{{ const_local_programming_param }}", value: "{{ const_local_programming_disable }}" }

          # setup local control
          - if:
              - condition: template
                value_template: "{{ local_control != 'undefined' }}"
            then:
              - alias: "zwavejs: Setup local control"
                service: zwave_js.set_config_parameter
                target: { device_id: "{{ device_id }}" }
                data: { parameter: "{{ const_local_control_param }}", value: "{{ local_control }}" }

      # button press event
      - conditions: "{{ scene_id == 'Scene 001' }}"
        sequence:
          - choose:
              - { conditions: "{{ event_action == 'KeyPressed' }}",   sequence: !input button_1_1x }
              - { conditions: "{{ event_action == 'KeyPressed2x' }}", sequence: !input button_1_2x }
              - { conditions: "{{ event_action == 'KeyPressed3x' }}", sequence: !input button_1_3x }
              - { conditions: "{{ event_action == 'KeyPressed4x' }}", sequence: !input button_1_4x }
              - { conditions: "{{ event_action == 'KeyPressed5x' }}", sequence: !input button_1_5x }
              - conditions: "{{ event_action == 'KeyHeldDown' }}"
                sequence:
                  - repeat:
                      sequence:
                        - if: "{{ not button_1_hold in ('none', 'null', 'unavailable', '') }}"
                          then: !input button_1_hold
                        - delay:
                            milliseconds: !input button_1_loop_hold_delay
                      until:
                        - condition: template
                          value_template: "{{ not is_loop_button_1_hold }}"
              - { conditions: "{{ event_action == 'KeyReleased' }}",  sequence: !input button_1_release }
      - conditions: "{{ scene_id == 'Scene 002' }}"
        sequence:
          - choose:
              - { conditions: "{{ event_action == 'KeyPressed' }}",   sequence: !input button_2_1x }
              - { conditions: "{{ event_action == 'KeyPressed2x' }}", sequence: !input button_2_2x }
              - { conditions: "{{ event_action == 'KeyPressed3x' }}", sequence: !input button_2_3x }
              - { conditions: "{{ event_action == 'KeyPressed4x' }}", sequence: !input button_2_4x }
              - { conditions: "{{ event_action == 'KeyPressed5x' }}", sequence: !input button_2_5x }
              - conditions: "{{ event_action == 'KeyHeldDown' }}"
                sequence:
                  - repeat:
                      sequence:
                        - if: "{{ not button_2_hold in ('none', 'null', 'unavailable', '') }}"
                          then: !input button_2_hold
                        - delay:
                            milliseconds: !input button_2_loop_hold_delay
                      until:
                        - condition: template
                          value_template: "{{ not is_loop_button_2_hold }}"
              - { conditions: "{{ event_action == 'KeyReleased' }}",  sequence: !input button_2_release }
